apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-deployment
  labels:
    app: factorial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: festive_kowalevski
        image: stantushaar/sdm_lab217:1.0
        